version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Build Mesh Node Espressobin
          command: './build massmesh meshnode espressobin'
      - store_artifacts:
          path: './communities/massmesh/meshnode/bin/espressobin'
      - run:
          name: Build Mesh Radio NS 5AC Loco
          command: './build massmesh meshnode espressobin'
      - store_artifacts:
          path: './communities/massmesh/meshpoint/bin/ns5ac-loco'
